### List All Messages

GET http://localhost:3000/messages 




### Create A new Message
POST http://localhost:3000/messages 
content-type: application/json

{
    "content":"hi there"
}

### Get a Particular Message
Get http://localhost:3000/messages/5272
